export const ACCOMPANIMENT_FAMILIES = ["Pommes de terre", "Légumes", "Céréales & légumineuses", "Gratins & purées", "Frais"] as const;
export const ACCOMPANIMENT_DIFFICULTIES = ["Facile", "Intermédiaire", "Délicat"] as const;
export const ACCOMPANIMENT_HOLDINGS = ["Excellente", "Bonne", "Courte"] as const;
export const ACCOMPANIMENT_DISPATCHES = ["Très rapide", "Rapide", "À la minute"] as const;

export type AccompanimentFamily = typeof ACCOMPANIMENT_FAMILIES[number];
export type AccompanimentDifficulty = typeof ACCOMPANIMENT_DIFFICULTIES[number];
export type AccompanimentHolding = typeof ACCOMPANIMENT_HOLDINGS[number];
export type AccompanimentDispatch = typeof ACCOMPANIMENT_DISPATCHES[number];

export type AccompanimentIdea = {
  name: string;
  family: AccompanimentFamily;
  difficulty: AccompanimentDifficulty;
  holding: AccompanimentHolding;
  dispatch: AccompanimentDispatch;
  serviceNote: string;
};

export const ACCOMPANIMENT_IDEAS: AccompanimentIdea[] = [
  {
    name: "Frites maison",
    family: "Pommes de terre",
    difficulty: "Délicat",
    holding: "Courte",
    dispatch: "À la minute",
    serviceNote: "Frire minute, bien égoutter et saler juste avant l’envoi.",
  },
  {
    name: "Pommes grenailles rôties",
    family: "Pommes de terre",
    difficulty: "Facile",
    holding: "Excellente",
    dispatch: "Très rapide",
    serviceNote: "Maintenir sur plaque chaude et raviver au four avant dressage.",
  },
  {
    name: "Écrasé de pommes de terre",
    family: "Pommes de terre",
    difficulty: "Facile",
    holding: "Bonne",
    dispatch: "Très rapide",
    serviceNote: "Garder couvert au bain-marie et détendre avant le service.",
  },
  {
    name: "Pommes boulangères",
    family: "Pommes de terre",
    difficulty: "Facile",
    holding: "Excellente",
    dispatch: "Très rapide",
    serviceNote: "Tenir en bac couvert et servir à la spatule.",
  },
  {
    name: "Pommes dauphine",
    family: "Pommes de terre",
    difficulty: "Intermédiaire",
    holding: "Courte",
    dispatch: "À la minute",
    serviceNote: "Frire par petites séries et maintenir brièvement sur grille.",
  },
  {
    name: "Galette de pommes de terre",
    family: "Pommes de terre",
    difficulty: "Intermédiaire",
    holding: "Bonne",
    dispatch: "Rapide",
    serviceNote: "Précuire puis croustiller à la poêle ou au four.",
  },
  {
    name: "Ratatouille confite",
    family: "Légumes",
    difficulty: "Facile",
    holding: "Excellente",
    dispatch: "Très rapide",
    serviceNote: "Maintenir en cocotte et mélanger doucement avant chaque portion.",
  },
  {
    name: "Carottes Vichy",
    family: "Légumes",
    difficulty: "Facile",
    holding: "Bonne",
    dispatch: "Très rapide",
    serviceNote: "Tenir avec leur jus et glacer au dernier moment.",
  },
  {
    name: "Chou vert braisé",
    family: "Légumes",
    difficulty: "Facile",
    holding: "Excellente",
    dispatch: "Très rapide",
    serviceNote: "Réchauffer couvert et ajouter le jus réduit à l’envoi.",
  },
  {
    name: "Haricots verts persillés",
    family: "Légumes",
    difficulty: "Délicat",
    holding: "Courte",
    dispatch: "À la minute",
    serviceNote: "Sauter minute et finir au beurre persillé.",
  },
  {
    name: "Champignons de Paris sautés",
    family: "Légumes",
    difficulty: "Intermédiaire",
    holding: "Courte",
    dispatch: "À la minute",
    serviceNote: "Sauter en petites quantités et dresser sans attente.",
  },
  {
    name: "Petits pois à la française",
    family: "Légumes",
    difficulty: "Facile",
    holding: "Bonne",
    dispatch: "Rapide",
    serviceNote: "Tenir en sauteuse couverte et remuer délicatement.",
  },
  {
    name: "Endives braisées",
    family: "Légumes",
    difficulty: "Intermédiaire",
    holding: "Excellente",
    dispatch: "Rapide",
    serviceNote: "Réchauffer dans le jus et bien égoutter au dressage.",
  },
  {
    name: "Courgettes rôties citron-thym",
    family: "Légumes",
    difficulty: "Facile",
    holding: "Bonne",
    dispatch: "Rapide",
    serviceNote: "Rôtir par plaques et réchauffer vivement sans ramollir.",
  },
  {
    name: "Lentilles vertes mijotées",
    family: "Céréales & légumineuses",
    difficulty: "Facile",
    holding: "Excellente",
    dispatch: "Très rapide",
    serviceNote: "Maintenir doucement en cocotte et ajuster le jus.",
  },
  {
    name: "Haricots blancs à la tomate",
    family: "Céréales & légumineuses",
    difficulty: "Facile",
    holding: "Excellente",
    dispatch: "Très rapide",
    serviceNote: "Tenir à feu doux et mélanger sans écraser.",
  },
  {
    name: "Riz pilaf aux oignons",
    family: "Céréales & légumineuses",
    difficulty: "Facile",
    holding: "Bonne",
    dispatch: "Très rapide",
    serviceNote: "Conserver couvert et égrainer avant chaque envoi.",
  },
  {
    name: "Semoule aux herbes",
    family: "Céréales & légumineuses",
    difficulty: "Facile",
    holding: "Bonne",
    dispatch: "Très rapide",
    serviceNote: "Garder couverte, aérer puis ajouter les herbes.",
  },
  {
    name: "Polenta crémeuse",
    family: "Céréales & légumineuses",
    difficulty: "Intermédiaire",
    holding: "Bonne",
    dispatch: "Rapide",
    serviceNote: "Maintenir souple au bain-marie et détendre avant l’envoi.",
  },
  {
    name: "Épeautre aux légumes racines",
    family: "Céréales & légumineuses",
    difficulty: "Intermédiaire",
    holding: "Excellente",
    dispatch: "Très rapide",
    serviceNote: "Tenir couvert et réchauffer avec un peu de bouillon.",
  },
  {
    name: "Gratin dauphinois",
    family: "Gratins & purées",
    difficulty: "Facile",
    holding: "Excellente",
    dispatch: "Rapide",
    serviceNote: "Cuire en plaques, portionner net puis réchauffer au four.",
  },
  {
    name: "Purée de céleri-rave",
    family: "Gratins & purées",
    difficulty: "Facile",
    holding: "Bonne",
    dispatch: "Très rapide",
    serviceNote: "Garder au bain-marie et lisser avant dressage.",
  },
  {
    name: "Purée de carottes au cumin",
    family: "Gratins & purées",
    difficulty: "Facile",
    holding: "Bonne",
    dispatch: "Très rapide",
    serviceNote: "Tenir couverte et fouetter brièvement avant dressage.",
  },
  {
    name: "Gratin de chou-fleur",
    family: "Gratins & purées",
    difficulty: "Facile",
    holding: "Excellente",
    dispatch: "À la minute",
    serviceNote: "Préportionner puis colorer sous salamandre à la commande.",
  },
  {
    name: "Coquillettes gratinées au comté",
    family: "Gratins & purées",
    difficulty: "Intermédiaire",
    holding: "Excellente",
    dispatch: "À la minute",
    serviceNote: "Cuire en bacs et gratiner la portion sous salamandre.",
  },
  {
    name: "Salade verte à l’échalote",
    family: "Frais",
    difficulty: "Délicat",
    holding: "Courte",
    dispatch: "À la minute",
    serviceNote: "Assaisonner à la commande et dresser sans tasser.",
  },
  {
    name: "Céleri rémoulade",
    family: "Frais",
    difficulty: "Facile",
    holding: "Bonne",
    dispatch: "Très rapide",
    serviceNote: "Conserver froid et mélanger avant de servir.",
  },
  {
    name: "Carottes râpées au citron",
    family: "Frais",
    difficulty: "Facile",
    holding: "Bonne",
    dispatch: "Très rapide",
    serviceNote: "Garder au froid et rectifier l’assaisonnement avant l’envoi.",
  },
  {
    name: "Concombre à la crème et aneth",
    family: "Frais",
    difficulty: "Facile",
    holding: "Courte",
    dispatch: "Rapide",
    serviceNote: "Conserver égoutté et napper de crème à la commande.",
  },
  {
    name: "Salade de betteraves aux noix",
    family: "Frais",
    difficulty: "Facile",
    holding: "Bonne",
    dispatch: "Très rapide",
    serviceNote: "Tenir au froid et ajouter les noix au dressage.",
  },
  {
    name: "Pommes Pont-Neuf",
    family: "Pommes de terre",
    difficulty: "Délicat",
    holding: "Courte",
    dispatch: "À la minute",
    serviceNote: "Faire la seconde cuisson à la commande, égoutter puis saler aussitôt.",
  },
  {
    name: "Gnocchis poêlés au beurre de sauge",
    family: "Pommes de terre",
    difficulty: "Délicat",
    holding: "Courte",
    dispatch: "À la minute",
    serviceNote: "Colorer à la poêle par petites portions et envoyer immédiatement.",
  },
  {
    name: "Épinards frais tombés au beurre",
    family: "Légumes",
    difficulty: "Délicat",
    holding: "Courte",
    dispatch: "À la minute",
    serviceNote: "Tomber rapidement à la commande, assaisonner et bien égoutter.",
  },
  {
    name: "Chou-fleur rôti au beurre noisette",
    family: "Légumes",
    difficulty: "Délicat",
    holding: "Courte",
    dispatch: "À la minute",
    serviceNote: "Précuire puis colorer vivement avec le beurre noisette à l’envoi.",
  },
  {
    name: "Beignets de courgette",
    family: "Légumes",
    difficulty: "Délicat",
    holding: "Courte",
    dispatch: "À la minute",
    serviceNote: "Frire à la commande, égoutter sur grille et servir sans attendre.",
  },
];
